State.create(name: "ALABAMA", abrev: "AL", url: "http://www.ancestry.com/wiki/images/archive/c/ca/20100415182343!Alabama_sil.png")
State.create(name: "ALASKA", abrev: "AK", url: "http://i.ebayimg.com/00/s/NDIwWDU3Ng==/z/VP8AAOxyE-dRy2~-/$T2eC16JHJHsFGlGzglvJBRy2+-WL2Q~~60_35.png")
State.create(name: "ARIZONA", abrev: "AZ", url: "http://www.ancestry.com/wiki/images/f/f5/Arizona_sil.png")
State.create(name: "ARKANSAS", abrev: "AR", url: "http://www.ancestry.com/wiki/images/b/b0/Arkansas_sil.png")
State.create(name: "CALIFORNIA", abrev: "CA", url: "http://www.ancestry.com/wiki/images/6/65/California_sil.png")
State.create(name: "COLORADO", abrev: "CO", url: "http://www.ancestry.com/wiki/images/f/f6/Colorado_sil.png")
State.create(name: "CONNECTICUT", abrev: "CT", url: "http://www.locksmithtrainingu.com/wp-content/uploads/2011/06/connecticut-map-silhouette.jpg")
State.create(name: "DELAWARE", abrev: "DE", url: "http://www.ancestry.com/wiki/images/8/8e/Delaware_sil.png")
State.create(name: "FLORIDA", abrev: "FL", url: "http://www.ancestry.com/wiki/images/1/1a/Flordia_sil.png")
State.create(name: "GEORGIA", abrev: "GA", url: "http://www.ancestry.com/wiki/images/5/5c/Georgia_sil.png")
State.create(name: "HAWAII", abrev: "HI", url: "http://www.ancestry.com/wiki/images/5/5a/Hawaii_sil.png")
State.create(name: "IDAHO", abrev: "ID", url: "http://www.ancestry.com/wiki/images/7/7e/Idaho_sil.png")
State.create(name: "ILLINOIS", abrev: "IL", url: "http://www.ancestry.com/wiki/images/5/58/Illinois_sil.png")
State.create(name: "INDIANA", abrev: "IN", url: "http://www.ancestry.com/wiki/images/4/4d/Indiana_sil.png")
State.create(name: "IOWA", abrev: "IA", url: "http://www.ancestry.com/wiki/images/4/48/Iowa_sil.png")
State.create(name: "KANSAS", abrev: "KS", url: "http://www.ancestry.com/wiki/images/4/46/Kansas_sil.png")
State.create(name: "KENTUCKY", abrev: "KY", url: "http://www.ancestry.com/wiki/images/b/b3/Kentucky_sil.png")
State.create(name: "LOUISIANA", abrev: "LA", url: "http://www.ancestry.com/wiki/images/7/7c/Louisiana_sil.png")
State.create(name: "MAINE", abrev: "ME", url: "http://www.ancestry.com/wiki/images/6/6a/Maine_sil.png")
State.create(name: "MARYLAND", abrev: "MD", url: "http://www.ancestry.com/wiki/images/6/6b/Maryland_sil.png")
State.create(name: "MASSACHUSETTS", abrev: "MA", url: "http://www.customwallgraphics.com/product_images/y/462/MA_US_State_Shape_Diecut_Vinyl_Decal__38700_zoom.jpg")
State.create(name: "MICHIGAN", abrev: "MI", url: "http://www.ancestry.com/wiki/images/f/f5/Michigan_sil.png")
State.create(name: "MINNESOTA", abrev: "MN", url: "http://www.worldatlas.com/webimage/countrys/namerica/usstates/outline/mn.gif")
State.create(name: "MISSISSIPPI", abrev: "MS", url: "http://www.netstate.com/states/maps/images/ms_outline.gif")
State.create(name: "MISSOURI", abrev: "MO", url: "http://www.ancestry.com/wiki/images/5/5e/Missouri_sil.png")
State.create(name: "MONTANA", abrev: "MT", url: "http://www.ancestry.com/wiki/images/4/49/Montana_sil.png")
State.create(name: "NEBRASKA", abrev: "NE", url: "http://www.ancestry.com/wiki/images/e/ee/Nebraska_sil.png")
State.create(name: "NEVADA", abrev: "NV", url: "http://www.ancestry.com/wiki/images/a/a3/Nevada_sil.png")
State.create(name: "NEW HAMPSHIRE", abrev: "NH", url: "http://www.ancestry.com/wiki/images/4/4c/NewHampshire_sil.png")
State.create(name: "NEW JERSEY", abrev: "NJ", url: "http://www.ancestry.com/wiki/images/1/11/NewJersey_sil.png")
State.create(name: "NEW MEXICO", abrev: "NM", url: "http://www.clker.com/cliparts/7/5/e/3/13148996251441839744New%20Mexico%20Outline.svg.med.png")
State.create(name: "NEW YORK", abrev: "NY", url: "http://0.tqn.com/d/gonewengland/1/0/i/5/newyorkmap.jpg")
State.create(name: "NORTH CAROLINA", abrev: "NC", url: "http://www.ancestry.com/wiki/images/6/6f/North-Carolina_sil.png")
State.create(name: "NORTH DAKOTA", abrev: "ND", url: "http://www.ancestry.com/wiki/images/8/8b/North-Dakota_sil.png")
State.create(name: "OHIO", abrev: "OH", url: "http://www.ancestry.com/wiki/images/0/00/Ohio_sil.png")
State.create(name: "OKLAHOMA", abrev: "OK", url: "http://www.ancestry.com/wiki/images/b/b7/Oklahoma_sil.png")
State.create(name: "OREGON", abrev: "OR", url: "http://www.ancestry.com/wiki/images/4/48/Oregon_sil.png")
State.create(name: "PENNSYLVANIA", abrev: "PA", url: "http://www.ancestry.com/wiki/images/9/91/Pennsylvania_sil.png")
State.create(name: "RHODE ISLAND", abrev: "RI", url: "http://www.ancestry.com/wiki/images/4/41/RhodeIsland_sil.png")
State.create(name: "SOUTH CAROLINA", abrev: "SC", url: "http://www.ancestry.com/wiki/images/8/85/SouthCarolina_sil.png")
State.create(name: "SOUTH DAKOTA", abrev: "SD", url: "http://www.ancestry.com/wiki/images/0/02/SouthDakota_sil.png")
State.create(name: "TENNESSEE", abrev: "TN", url: "http://www.ancestry.com/wiki/images/b/bc/Tennessee_sil.png")
State.create(name: "TEXAS", abrev: "TX", url: "http://www.ancestry.com/wiki/images/a/ac/Texas_sil.png")
State.create(name: "UTAH", abrev: "UT", url: "http://www.ancestry.com/wiki/images/d/d0/Utah_sil.png")
State.create(name: "VERMONT", abrev: "VT", url: "http://www.ancestry.com/wiki/images/8/87/Vermont_sil.png")
State.create(name: "VIRGINIA", abrev: "VA", url: "http://www.ancestry.com/wiki/images/4/40/Virginia_sil.png")
State.create(name: "WASHINGTON", abrev: "WA", url: "http://ntl.bts.gov/lib/jpodocs/repts_te/14128/images/main/washington.jpg")
State.create(name: "WEST VIRGINIA", abrev: "WV", url: "http://www.ancestry.com/wiki/images/c/c7/WestVirginia_sil.png")
State.create(name: "WISCONSIN", abrev: "WI", url: "http://www.ancestry.com/wiki/images/4/4d/Wisconsin_sil.png")
State.create(name: "WYOMING", abrev: "WY", url: "http://www.ancestry.com/wiki/images/3/37/Wyoming_sil.png")
